# -*- coding: utf-8 -*-
"""Predic BTC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BB5BQUZSNlOG_JmSebzf0pqYTAJxPT9-

# Laporan Proyek Machine Learning - I Kadek Adi Memes Subagia

# Domain Proyek
 <h1>Analisa Pergerakan Harga Bitcoin</h1>

 <p>Bitcoin atau yang biasa kita kenal dengan BTC adalah salah satu mata uang digital atau yang kita kenal dengan cryptocurrency, hal ini menjadi sangat tren dan banyak sekali orang -orang yang mulai menaruh sebagian penghasilannya kedalam cryptocurrency. terutama pada Bitcoin ini karena Bitcoin menduduki Top 1 cryptocurrency dengan harga market tertinggi. bisa dilihat pada website <a href ="https://coinmarketcap.com/id/">Coinmarketcap</a></p> <br>
 Kenapa saya mengambil permasalahan ini adalah karena ini sedang panas - panasnya di indonesia, dimana banyak konten kreator yang sudah mengedukasi kita untuk mulai investasi pada coin inii, tapii kita sebagai individu tidak boleh asal percaya dengan ajakan konten kreator yang mengajak menaruh uang kita pada Bitcoin sebelum kita tahu apa itu Bitcoin?? dan apa aja sihh yang mempengaruhi Bitcoin itu bisa naik atau turun. <br>

 Nahhh karena ini adalah uang digital yang harganya tidak bisa di prediksi dengan hanya insting kita hehehehe, kita perlu adanya pemahaman mengenai cryptocurrency dan pada kesempatan ini saya mencoba mengambil contoh di Bitcoin.

# Business Understanding

Dari Latar belakang di atas mengenai kenapa saya mengambil contoh ini pada proyek saya, saya mendapati dua problem yaitu:

## Problem
*   Apa Saja Faktor yang mempengaruhi Kenaikan dan penurunan Harga Bitcoin ?
*   Apakah Bitcoin Layak di Investasikan Jangka Panjang ?

## Goals

*   Memeriksa faktor yang memiliki Hubungan erat dengan Harga Bitcoin
*   Membuat sebuah Model yang bisa memberikan prediksi harga Bitcoin satu tahun kedepan, dengan data yang ada.

## Solution statements

*   Untuk Permasalahan pertama saya akan membuat sebuah visualisasi data berupa heatmap yang menunjukan korelasi antar setiap fitur dari Bitcoin untuk melihat fitur apa saja yang memiliki korelasi dari harga bitcoin
*   Permasalahan kedua saya akan membuat sebuah model prediksi menggunakan algoritma Random Forest untuk memprediksi harga dengan menggunakan data yang saya miliki.

## Mempersiapkan Envirotment

pada proyek ini saya menggunakan beberapa libary python yaitu:

*   Pandas
*   numpy
*   matplotlib
*   Seaborn

Dan pada proyek ini saya menggunakan algoritma supervised learning yaitu Random Forest
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sbn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, accuracy_score, precision_score, recall_score, f1_score

"""# Data Understanding

Untuk menyelesaikan masalah yang sudah saya sampaikan di atas, disini saya akan menggunakan dataset yang disediakan secara grartis pada Kaggle <br>
[Dataset](https://www.kaggle.com/datasets/sudalairajkumar/cryptocurrencypricehistory/data) <br>

data yang saya ambil adalah data historical dari Cryptocurrency dalam dataset ini terdapat 23 historical dari Cryptocurrency yang ada, namun karena latar belakang ini mengenai Bitcoin jadi saya hanya mengambil data untuk coin BTC saja.

## Mengambil Dataset Yang Sudah Di Download
"""

url = "/content/drive/MyDrive/coin_Bitcoin.csv"
BTC = pd.read_csv(url)

BTC

"""Dari Data tersebut Terlihat pada daaset ini terdapat 2991 baris yang terdiri dari 10 kolom:

*   SNo : yang menunjukan nomor dari data
*   Name : adalah menunjukan nama coin dari Cryptocurrency yaitu Bitcoin
*   Symbol : yaitu symbol dari nama Bitcoin yaitu BTC
*   Date : menunjukan tanggal data yang diambil yaitu mulai dari 2013 - 2021
*   High : kolom ini menunjukan harga tertinggi yang dicapai oleh Bitcoin berdasarkan tanggalnya
*   Low : ini adalah kebalikan dari Kolom HIgh, pada kolom ini menunjukan harga terendah dari Bitcoin pada Tanggal tersebut
*   Open : kolom ini merupakan harga pembuka dari koin Bitcoin
*   CLose : yang merupakan harga penutup dari Bitcoin di tanggal tersebut
*   Marketcap : kolom ini menunjukan berapa total aset Bitcoin yang berada dalam pasar Crypto

## EDA (Eksplorasi Data Analysis)

Disini saya akan mencoba menelusuri data dari histori Bitcoin, apakah terdapat missing value, datatype yang salah dan mencoba memvisualisasi data untuk menyelesaikan permasalahan yang ada di latar belakang.
"""

BTC.shape

BTC.info()

"""Dari Info ini bisa dilihat terdapat kesalahan type data yang ada, yang mana pada kolom Date seharusnya bertype datetime namun pada data ini bertipe object. maka kita harus memperbaikinya"""

BTC.isnull().sum()

"""Dilihat Dari Data Tidak ada memiliki missing value.

Memperbaiki Dataset
"""

BTC['Date'] = pd.to_datetime(BTC['Date'])
BTC.sort_values(by='Date', inplace=True)

BTC.info()

"""Type Data sudah Di perbaiki.

## Pergerakan Harga Crypto

Disini saya mencoba untuk memvisualisasikan Pergerakan Harga Bitcoin dari awal data sampe data yang terakhir dengan memanfaatkan beberapa kolom yaitu:

*   Open
*   Close
*   High
*   Low
*   Date

disini saya membuat data Open, Close, High dan Low memiliki warna masing-masing supaya lebih jelas untuk dilihat, kemudian saya buat date berada pada label X dan menambahkan label y dengan nama Price (USD)
"""

plt.figure(figsize=(14, 7))

plt.plot(BTC['Date'], BTC['Open'], label='Harga Pembuka BTC', color='yellow')
plt.plot(BTC['Date'], BTC['Close'], label='Harga Penutupan BTC', color='Green')
plt.plot(BTC['Date'], BTC['High'], label='Harga Tertinggi BTC', color='blue')
plt.plot(BTC['Date'], BTC['Low'], label='Harga Terendah BTC', color='red')
plt.title('Pergerakan Harga BTC Waktu ke Waktu')
plt.xlabel('Date')
plt.ylabel('Price (USD)')
plt.legend()
plt.show()

"""Dilihat Dari Data Ini Pergerakan Bitcoin dari 4 tahun terakhir yaitu 2018 - 2021 mengalami kenaikan yang sangat pesat.

### Bagaimana Rata - Rata Harga Penutupan Pada jangka Tahunan, Bulanan dan Minggu

Saya memvisualisasikan supaya mengetahui seberapa drastis kenaikan dan penurunan koin Bitcoin pada jangkoan Tahun,Bulan dan Minggu
"""

# convert kolom data menjadi datetime.
BTC['Date'] = pd.to_datetime(BTC['Date'])

# Menghitung rata-rata harga penutup per tahun Calculate
BTC['Year'] = BTC['Date'].dt.year
yearly_trend = BTC.groupby('Year')['Close'].mean()

# Menghitung rata-rata harga penutup per Bulan Calculate
BTC['Month'] = BTC['Date'].dt.to_period('M')
monthly_trend = BTC.groupby('Month')['Close'].mean()

# Menghitung rata-rata harga penutup per Minggu Calculate
BTC['Week'] = BTC['Date'].dt.to_period('W')
weekly_trend = BTC.groupby('Week')['Close'].mean()


plt.figure(figsize=(14, 10))

# Visualisasi Tahun
plt.subplot(3, 1, 1)
yearly_trend.plot(marker='o', color='blue')
plt.title('Harga penutupan rata-rata tahunan Bitcoin')
plt.xlabel('Tahun')
plt.ylabel('Price (USD)')
plt.grid(True)

# Visualisasi Bulan
plt.subplot(3, 1, 2)
monthly_trend.plot(marker='o', color='orange')
plt.title('Harga penutupan rata-rata Bulanan Bitcoin')
plt.xlabel('Bulan')
plt.ylabel('Price (USD)')
plt.grid(True)

# Visualisasi Minggu
plt.subplot(3, 1, 3)
weekly_trend.plot(marker='o', color='green')
plt.title('Harga penutupan rata-rata Mingguan Bitcoin')
plt.xlabel('Minggu')
plt.ylabel('Price (USD)')
plt.grid(True)

plt.tight_layout()
plt.show()

"""Dilihat Dari 3 Grafik Di atas Bisa:


*   Pada Grafik Tahunan, Bisa dilihat Kenaikan Nilai Bitcoin dimulai dari tahun 2016 sampai 2021, kenaikan yang dialami terus menerus.
*   Pada Grafik kedua terlihat lonjakan yang cukup tinggi pada bulan 2020 sampai 2021 dan kemudian mengalami koreksi untuk menjaga harga pasa.
*   Pada Grafik ketiga kita bisa melihat dengan jelas bagaimana flukuatifnya harga Bitcoin di pasar, kita bisa melihat dimana bitcoin sempat naik pada tahun 2017 - 2018 dan mengalami koreksi kemudian meningkat lagi pada tahun 2020 - 2021.

Kesimpulan dari grafik ini adalah puncak dari harga BTC atau All Time High nya berada pada maret 2021. dan bisa disimpulkan juga Bitcoin bisa menjadi salah satu pilihan investasi jika dilihat dari grafiknya

## Melihat Korelasi Dari BTC

Untuk menjawab pertanyaan pertama pada latar belakang yaitu: <br>
"Apa Saja Faktor yang mempengaruhi Kenaikan dan penurunan Harga Bitcoin ?" <br>
saya menggunakan teknik visualisasi Heatmap guna mengetahui korelasi dari setiap feature yang ada dalam Data Bitcoin tersebut. <br>
dengan berpacu pada kolom Close yang merupakan harga penutup dari Bitcoin
"""

numerical_features = BTC.select_dtypes(include=['number'])

plt.figure(figsize=(10, 6))
sbn.heatmap(numerical_features.corr(), annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
plt.title('Heatmap Korelasi Fitur Bitcoin')
plt.show()

"""## Fitur Yang mempengaruhi Harga Bitcoin

Dilihat dari Heatmap di atas, kita bisa melihat bahwa yang memiliki korelasi kuat dengan harga Bitcoin yaitu:


*   Open
*   Low
*   High
*   Marketcap

Jadi untuk menmbuat prediksi dari harga BTC kita bisa menggunakan fitur tersebut menjadi acuannya. dengan targetnya dalah close yaang merupakan harga penutupan dari Bitcoin<br>

jadi bisa disimpulkan untuk jawaban dari permasalahan pertama sudah bisa dijawab.

# Modeling dan Evaluasi

Untuk Menjawab pertanyaan nomor dua saya menggunakan algoritma random forest.  <br>

## Random Forest
menggunakan Random Forest karena menurut saya algoritma ini cocok untuk menangani data yang lumayan kompleks, walaupun pada permaslahaan ini memiliki kekurangan juga yaitu kurang akurat untuk memprediksi jangka panjang dan ada alternatifnya yaitu menggunakan LSTM (Long Short-Term Memory) <br> namun karen saya belum mengetahui mengenai LSTM (Long Short-Term Memory) saya akan menggunakan Random Forest Untuk kasus ini

# Algoritma Random Forest
"""

# Pastikan BTC hanya memiliki fitur yang dipilih
BTC = BTC[['Open', 'High', 'Low', 'Volume', 'Marketcap', 'Close']]

# Pilih fitur dan target
X = BTC[['Open', 'High', 'Low', 'Volume', 'Marketcap']]
y = BTC['Close']

# Split data untuk training dan testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Inisialisasi model Random Forest
rf = RandomForestRegressor(n_estimators=50, random_state=42)

# Latih model
rf.fit(X_train, y_train)

# Prediksi pada data testing
# Use X_test for prediction to get predictions for the test set
y_pred = rf.predict(X_test)

# Evaluasi model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Print hasil evaluasi
print(f"Mean Absolute Error (MAE): {mae}")
print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")
print(f"R-squared (R²) Score: {r2}")

"""Dari Hasil Evaluasi kita bisa melihat nilai yang didapatkan perfoma dari Model yang kita gunakan. <br>



*   Mean Absolute Error (MAE): 53.313980195671896
*   Mean Squared Error (MSE): 15065.236109044139
*   Root Mean Squared Error (RMSE): 122.74052349995962
*   R-squared (R²) Score: 0.9998463119068502

# Testing Model

Disini saya mencoba menggunakan Testing model untuk prediksi harga Bitcoin Satu Tahun kedepan
"""

# Simpan prediksi selama 365 hari
future_prices = []
latest_data = X.iloc[-1:].copy()  # Ambil data terbaru

# Prediksi selama 365 hari ke depan
for i in range(365):
    latest_data['Volume'] *= 1.01  # Naik 1% per hari
    latest_data['Marketcap'] *= 1.005  # Naik 0.5% per hari

    # Prediksi harga BTC
    predicted_price = rf.predict(latest_data[['Open', 'High', 'Low', 'Volume', 'Marketcap']])[0]
    future_prices.append(predicted_price)

    # Update latest_data dengan harga prediksi terbaru
    latest_data['Open'] = predicted_price
    latest_data['High'] = predicted_price * 1.01
    latest_data['Low'] = predicted_price * 0.99

# Simpan hasil prediksi ke dalam DataFrame
future_df = pd.DataFrame({'Hari': np.arange(1, 366), 'Prediksi Harga BTC': future_prices})

# Menampilkan prediksi untuk 1 tahun mendatang
print(future_df)

"""# Kesimpulan

Dari Hasil Evaluasi tersebut saya bisa ambil kesimpulan bahwa Model yang menggunakan algoritma random forest berjalan dengan baik, dengan nilai R2 mendekati 1, tetapi tidak menutup kemungkinan nilai tersebut buruk karena overfiting dari data.<br>

apakah ini bisa menjawab pertanyaan Nomor 2??? <br>
menurut saya bisa digunakan, namun perlu diingatkan pada dunia Crypto ada banyak faktor lainnya, mulai dari berita suku bunga AS, kebijakan pemerintah dan lainnya lagi. <br>
namun model ini menurut saya bisa di pakai jika hanya untuk memvisualisasi prediksi saja.
"""